# Use the latest Node.js base image
FROM node:latest

# Set the working directory inside the container
WORKDIR ./app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Build the Next.js application
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Start the Next.js server
CMD [ "npm", "start" ]
